# Generated by Django 4.2.20 on 2025-06-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QAData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_title", models.TextField(verbose_name="问题标题")),
                (
                    "question_content",
                    models.TextField(blank=True, verbose_name="问题内容"),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="答主昵称"
                    ),
                ),
                (
                    "answer_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回答时间"
                    ),
                ),
                ("agree_count", models.IntegerField(default=0, verbose_name="赞同数")),
                (
                    "comment_count",
                    models.IntegerField(default=0, verbose_name="评论数"),
                ),
                ("answer_content", models.TextField(verbose_name="回答内容")),
                (
                    "word_segmentation",
                    models.TextField(blank=True, verbose_name="分词结果"),
                ),
                ("keywords", models.TextField(blank=True, verbose_name="关键词列表")),
            ],
        ),
    ]
